# Generated by Django 5.0.2 on 2024-02-20 05:00

import django.core.validators
import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_timesheet_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.FileField(upload_to=home.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('pan', models.FileField(upload_to=home.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
